apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
spec:
  type: NodePort
  ports:
  - name: nginx
    nodePort: 30200
    port: 8080 
    protocol: TCP
    targetPort: 80 
  selector:
    app: jenkins-test-pod
